### ISSUE TITLE
Need fix problem on postinst and postrm in deb file

### ISSUE THREAD

**Issue by ailtonbsj** [FlorianFe/Elements#15]
Try this:

File: `postinst`
```bash
#!/bin/bash

# Link to the binary
if [ -d /usr/local/bin/ ]; then
    ln -sf '/opt/Elements/elements' '/usr/local/bin/elements'
elif [ -d /usr/bin/ ]; then
    ln -sf '/opt/Elements/elements' '/usr/bin/elements'
fi
```

File: `postrm`
```bash
#!/bin/bash

# Delete the link to the binary
rm -f '/usr/local/bin/elements'
rm -f '/usr/bin/elements'
```

**Comment by FlorianFe** [comment]
I'm not so skilled in using Linux systems.

What doesn't work?
What error message shows up?

**Comment by ailtonbsj** [comment]
Your release `Elements.deb` has crashing in several system like Lubuntu because this systems doesn't have path of folders `/usr/local/bin/`. In this systems the bin folder it is `/usr/bin/`.
So you need check if folder exist before create a symbolic link on it.
If you don't do this the APT ou DPKG will crash.

I put the fixed deb file here: [go!](https://github.com/winunix/debian/tree/master/pool/main/e/elements)
And cite your app on [free apps catalog: here!](https://appsedu.github.io/catalog-apps/#Elements)

**Comment by FlorianFe** [comment]
The "Elements.deb" is generated by the [electron-builder](https://github.com/electron-userland/electron-builder). The electron-builder should take care of the interoperability through all the operating systems. 

In Elements 1.1.6 it used version 20.8.1. Now in version 1.2.1 it uses 22.7.0. So maybe they already improved that and it works in the newest Elements version. 

If it's still not working, you (because I'm not that well educated in linux things 😅) should also open your issue [there](https://github.com/electron-userland/electron-builder), because I guess then it will act the same for all electron applications using the electron-builder at the moment. 

Oh and thanks for citing my app! 😁

**Comment by ailtonbsj** [comment]
Your last release was fixed this problem. Thanks!
